### ISSUE TITLE
Using opencv cuda library functions on TX1 is very slow at 1FPS

### ISSUE THREAD

**Issue by tianxinyu0509** [PacktPublishing/Hands-On-GPU-Accelerated-Computer-Vision-with-OpenCV-and-CUDA#3]
I first tested the data addition code for the 50,000 members of the book on TX1, and it worked just fine.
![图片](https://user-images.githubusercontent.com/36063678/70608655-746a6780-1c3b-11ea-9b52-4cfcb70f2fc9.png)
But when I tested the image addition code, I only got 1FPS.
![图片](https://user-images.githubusercontent.com/36063678/70609114-3a4d9580-1c3c-11ea-8cb2-60103faf9db3.png)
book:
![图片](https://user-images.githubusercontent.com/36063678/70609180-581afa80-1c3c-11ea-85db-cdb960af34db.png)
my test:
![图片](https://user-images.githubusercontent.com/36063678/70609461-c95aad80-1c3c-11ea-8c02-9323d3e23988.png)
Does the tx1 have any NVIDIA drivers to install?I only installed the system and cuda as follows:
![图片](https://user-images.githubusercontent.com/36063678/70609661-2191af80-1c3d-11ea-9a5b-c19434c348ec.png)

**Comment by robotchaoX** [comment]
This may be due to the long time it takes for the GPU to start up the first time. If the loop is executed 5 times, you will find that only the first execution takes longer. The code and test results are as follows:
```
#include <iostream>
#include "opencv2/opencv.hpp"
#include "opencv2/core/cuda.hpp"
//#include <cuda_runtime.h>

int main(int argc, char *argv[])
{
    //Read Two Images
    cv::Mat h_img1 = cv::imread("images/cameraman.tif");
    cv::Mat h_img2 = cv::imread("images/circles.png");
    cv::Mat h_result1;
    // execute 5 times
    for (int i = 0; i < 5; i++)
    {
        int64 work_begin = cv::getTickCount();
        //Create Memory for storing Images on device
        cv::cuda::GpuMat d_result1, d_img1, d_img2;
        //Upload Images to device
        d_img1.upload(h_img1);
        d_img2.upload(h_img2);
        cv::cuda::add(d_img1, d_img2, d_result1);
        //Download Result back to host
        d_result1.download(h_result1);
        int64 delta = cv::getTickCount() - work_begin;
        double freq = cv::getTickFrequency();
        double work_fps = freq / delta;
        std::cout << "Performance of Addition on Jetson TX1: " << std::endl;
        std::cout << "Time: " << (1 / work_fps) << std::endl;
        std::cout << "FPS: " << work_fps << std::endl;
    }
    cv::imshow("Image1 ", h_img1);
    cv::imshow("Image2 ", h_img2);
    cv::imshow("Result addition ", h_result1);
    cv::imwrite("result_add.png", h_result1);
    cv::waitKey();
    return 0;
}
```
```
Performance of Addition on Jetson TX1: 
Time: 0.789957
FPS: 1.26589
Performance of Addition on Jetson TX1: 
Time: 0.00194754
FPS: 513.469
Performance of Addition on Jetson TX1: 
Time: 0.00159426
FPS: 627.25
Performance of Addition on Jetson TX1: 
Time: 0.00177029
FPS: 564.879
Performance of Addition on Jetson TX1: 
Time: 0.0016342
FPS: 611.921
```

**Comment by gaurav-packt** [comment]
Thanks for the feedback.

With this closing the issue.
